"""empty message

Revision ID: 074f45e08bab
Revises: d71f464c5174
Create Date: 2024-07-27 20:31:43.383923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074f45e08bab'
down_revision = 'd71f464c5174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_classification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_classification', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
