"""empty message

Revision ID: 20260ee05fa8
Revises: 9ad07de1fb57
Create Date: 2024-07-14 18:46:10.990283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260ee05fa8'
down_revision = '9ad07de1fb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
