"""empty message

Revision ID: 31456382ab3b
Revises: b1538f51bd4d
Create Date: 2024-07-13 16:37:16.996571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31456382ab3b'
down_revision = 'b1538f51bd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_name', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_vat',
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.PrimaryKeyConstraint('vat_id', 'user_id')
    )
    op.create_table('user_vat',
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.PrimaryKeyConstraint('vat_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vat')
    op.drop_table('admin_vat')
    op.drop_table('vat')
    # ### end Alembic commands ###
