"""empty message

Revision ID: 9ad07de1fb57
Revises: 6696f51f8358
Create Date: 2024-07-14 13:33:54.427063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad07de1fb57'
down_revision = '6696f51f8358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('disbursement_number', sa.String(), nullable=True),
    sa.Column('check_number', sa.String(), nullable=True),
    sa.Column('check_name_id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cash_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['check_name_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_disbursement',
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_id', 'user_id')
    )
    op.create_table('disbursement_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('not_applicable', sa.Float(), nullable=True),
    sa.Column('exempted', sa.Float(), nullable=True),
    sa.Column('zero_rated', sa.Float(), nullable=True),
    sa.Column('vat_registered', sa.Float(), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.Column('wtax_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('particulars', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.ForeignKeyConstraint(['wtax_id'], ['wtax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_disbursement',
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_disbursement')
    op.drop_table('disbursement_detail')
    op.drop_table('admin_disbursement')
    op.drop_table('disbursement')
    # ### end Alembic commands ###
