"""empty message

Revision ID: b3403ba393cb
Revises: 31456382ab3b
Create Date: 2024-07-14 10:57:58.689037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3403ba393cb'
down_revision = '31456382ab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wtax_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wtax_type_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_wtax_type',
    sa.Column('wtax_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wtax_type_id'], ['wtax_type.id'], ),
    sa.PrimaryKeyConstraint('wtax_type_id', 'user_id')
    )
    op.create_table('user_wtax_type',
    sa.Column('wtax_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wtax_type_id'], ['wtax_type.id'], ),
    sa.PrimaryKeyConstraint('wtax_type_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wtax_type')
    op.drop_table('admin_wtax_type')
    op.drop_table('wtax_type')
    # ### end Alembic commands ###
