"""empty message

Revision ID: b5b021608e09
Revises: 074f45e08bab
Create Date: 2024-08-05 03:20:34.592601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b021608e09'
down_revision = '074f45e08bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disbursement', schema=None) as batch_op:
        batch_op.alter_column('record_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disbursement', schema=None) as batch_op:
        batch_op.alter_column('record_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
