"""empty message

Revision ID: d71f464c5174
Revises: b28ac0a2d084
Create Date: 2024-07-27 16:49:59.493320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71f464c5174'
down_revision = 'b28ac0a2d084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_classification_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("account_classification_id_fk", 'account_classification', ['account_classification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_classification_id')

    # ### end Alembic commands ###
